//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace funny_neko_giver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("funny_neko_giver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copyfile_icon {
            get {
                object obj = ResourceManager.GetObject("copyfile_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string dialog_messages_error {
            get {
                return ResourceManager.GetString("dialog_messages.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while accessing API....
        /// </summary>
        internal static string error_accessapi {
            get {
                return ResourceManager.GetString("error.accessapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify category!.
        /// </summary>
        internal static string error_category {
            get {
                return ResourceManager.GetString("error.category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect API!
        ///{0}.
        /// </summary>
        internal static string error_connectapi {
            get {
                return ResourceManager.GetString("error.connectapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading image....
        /// </summary>
        internal static string error_downloadimage {
            get {
                return ResourceManager.GetString("error.downloadimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string form_button_deleteall {
            get {
                return ResourceManager.GetString("form.button.deleteall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downoad All.
        /// </summary>
        internal static string form_button_downloadall {
            get {
                return ResourceManager.GetString("form.button.downloadall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string form_button_load {
            get {
                return ResourceManager.GetString("form.button.load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string form_configure {
            get {
                return ResourceManager.GetString("form.configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Description.
        /// </summary>
        internal static string form_file_description {
            get {
                return ResourceManager.GetString("form.file_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        internal static string form_label_amount {
            get {
                return ResourceManager.GetString("form.label.amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current API:.
        /// </summary>
        internal static string form_label_currentapi {
            get {
                return ResourceManager.GetString("form.label.currentapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string form_tool_strip_about {
            get {
                return ResourceManager.GetString("form.tool_strip.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image.
        /// </summary>
        internal static string form_tool_strip_copyimage {
            get {
                return ResourceManager.GetString("form.tool_strip.copyimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Resized Image.
        /// </summary>
        internal static string form_tool_strip_copyresimage {
            get {
                return ResourceManager.GetString("form.tool_strip.copyresimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image URL.
        /// </summary>
        internal static string form_tool_strip_copyurl {
            get {
                return ResourceManager.GetString("form.tool_strip.copyurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string form_tool_strip_image {
            get {
                return ResourceManager.GetString("form.tool_strip.image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string form_tool_strip_main {
            get {
                return ResourceManager.GetString("form.tool_strip.main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (Local).
        /// </summary>
        internal static string form_tool_strip_save_local {
            get {
                return ResourceManager.GetString("form.tool_strip.save_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (Query).
        /// </summary>
        internal static string form_tool_strip_search {
            get {
                return ResourceManager.GetString("form.tool_strip.search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string form_tool_strip_zoomin {
            get {
                return ResourceManager.GetString("form.tool_strip.zoomin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string form_tool_strip_zoomout {
            get {
                return ResourceManager.GetString("form.tool_strip.zoomout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Zoom.
        /// </summary>
        internal static string form_tool_strip_zoomrestore {
            get {
                return ResourceManager.GetString("form.tool_strip.zoomrestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_icon {
            get {
                object obj = ResourceManager.GetObject("image_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap link_icon {
            get {
                object obj = ResourceManager.GetObject("link_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed!.
        /// </summary>
        internal static string progress_completed {
            get {
                return ResourceManager.GetString("progress.completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the API....
        /// </summary>
        internal static string progress_connectapi {
            get {
                return ResourceManager.GetString("progress.connectapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading an image... {0}/{1}.
        /// </summary>
        internal static string progress_downloadimage {
            get {
                return ResourceManager.GetString("progress.downloadimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching results....
        /// </summary>
        internal static string progress_fetching {
            get {
                return ResourceManager.GetString("progress.fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks running....
        /// </summary>
        internal static string progress_notasksrunning {
            get {
                return ResourceManager.GetString("progress.notasksrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_icon {
            get {
                object obj = ResourceManager.GetObject("save_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap websearch_icon {
            get {
                object obj = ResourceManager.GetObject("websearch_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoomin_icon {
            get {
                object obj = ResourceManager.GetObject("zoomin_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoomout_icon {
            get {
                object obj = ResourceManager.GetObject("zoomout_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
